name: Github Actions for MOPAC Docker Image
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Clone MOPAC repository
      uses: actions/checkout@v3

    - name: Docker Image BUILD
      run: docker build -t mopac-test .

    - name: Run MOPAC INPUT test on formic_acid
      run: docker run -v ${{ github.workspace }}:/input mopac-test formic_acid.mop

    - name: test output
      run: cat formic_acid.out
