name: Github Actions for MOPAC Docker Image
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Clone MOPAC repository
      uses: actions/checkout@v3
      
    - name: Create output directory on host
      run: mkdir -p ${{ github.workspace }}/output
      
    - name: Docker Image BUILD
      run: docker build -t mopac-test .

    - name: Run MOPAC INPUT test on formic_acid
      run: docker run --rm -v ${{ github.workspace }}:/input mopac-test formic_acid.mop

    - name: test output
      run: cat input/formic_acid.out

    - name: Print output from host
      run: |
        echo "Formic Acid MOPAC Output:"
        ls -l ${{ github.workspace }}/output
        cat ${{ github.workspace }}/output/formic_acid.out
