name: Github Actions for MOPAC Docker Image
on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout MOPAC repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t mopac-test .

    - name: Run MOPAC Input Test on formic_acid
      run: |
        docker run --rm -v ${{ github.workspace }}/output:/output mopac-test formic_acid.mop

    - name: Test Output
      run: |
        echo "Checking output directory:"
        ls -l ${{ github.workspace }}/output

    - name: Print Output from Host
      run: |
        echo "Formic Acid MOPAC Output:"
        cat ${{ github.workspace }}/output
